<header>
    <div class="header-items">
        <a href="/public/api/auctions">Spartan Auction</a>
    </div>
    <form class="search" action="">
        <input type="text" placeholder="Search . . .">
        <a href="./search.html"><i class="fa fa-search"></i></a>
    </form>
    <div class="sign-up-login">
        <a href="/public/users/login" class="link-button">Login</a>
        <a href="/public/users/signup" class="link-button">Sign Up</a>
    </div>
</header>