<header>
    <div class="header-items">
        <p class="small-header"><a href="./index.html">Spartan Auction</a></p>
    </div>
    <div class="search">
        <input type="text" placeholder="Search . . .">
        <a href="./search.html"><i class="fa fa-search"></i></a>
    </div>
    <div class="sign-up-login">
        <a href="/login" class="link-button">Login</a>
        <a href="/signup" class="link-button">Sign Up</a>
    </div>
</header>