<div class="user-nav">
    <a id="my-auctions-tab" class="user-nav-non-highlight">My Auctions</a>
    <a id="current-bids-tab" class="user-nav-highlight">Current Bids</a>
    <a id="past-bids-tab" class="user-nav-non-highlight">Past Bids</a>
    <a id="customer-reviews-tab" class="user-nav-non-highlight">Customer Reviews</a>
</div>

<!--<script src="/script/profile.js" type="text/javascript"></script>-->